# Generated by Django 5.2.4 on 2025-08-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
