# Generated by Django 5.2.4 on 2025-08-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_options_produto_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
